### ISSUE TITLE
Additional/New Ownership

### ISSUE THREAD

**Issue by trek** [abedra/urbanairship#59]
Although we still use Urban Airship at Groupon, our architecture has changed so that we're no longer using it via Ruby. This puts us into an awkward position as responsible stewards of this gem. 

We're on the lookout for additional maintainers in the short term and potentially new owners in the long term. Our immediate need is someone with context and experience to begin evaluating issues and pulls.

@joeyschoblaska has kindly offered to take over this gem if we can't find someone else, but ideally we'd find someone who uses this gem in their product and has some skin in the game.

If you use this gem in your products, please reach out so we can come up with a migration plan

**Comment by trek** [comment]
@dogweather any news?

**Comment by trek** [comment]
Closed! We've transfered.

**Comment by trek** [comment]
@dogweather is there an email we can use to transfer gem ownership: http://guides.rubygems.org/command-reference/#gem-owner

**Comment by dogweather** [comment]
Thanks - yes, please use my email `robb.shecter@urbanairship.com`. This is the email currently linked to the new account, https://rubygems.org/profiles/UrbanAirship

**Comment by trek** [comment]
added!

**Comment by dogweather** [comment]
Thanks! Everything looks good from here.
